### ISSUE TITLE
Reused code in isValidMove() method

### ISSUE THREAD

**Issue by edf42001** [THByt/Chess#3]
There are two things every valid move needs to be 

1. In bounds
2. Not the same square it started on

Should this be checked in each subclasses isValidMove() method with a method?
`isValidMove(){
   if(!(outOfBounds() || sameSquare()){
          //check for specific piece here
   }else{
    return false;
   }
`

or should we assume that the same Location the piece is on or an out of bounds Location is not passed to the method?

**Comment by THByt** [comment]
The latter suggestion makes more sense

**Comment by edf42001** [comment]
HAHA I made it your job now

**Comment by edf42001** [comment]
Although I don't think we need to check if it's out of bounds. Just don't pass it anything out of bounds

**Comment by THByt** [comment]
?!?!?!??!!?!?

**Comment by edf42001** [comment]
In the method, don't add any code to check if it's out of bounds. Just have
`isNotSameSquare && validMoveForPiece`

**Comment by THByt** [comment]
ik u already told me
